### ISSUE TITLE
Issue with design history animation

### ISSUE THREAD

**Issue by DoritoMojito** [FutureJames/Fusion360Plugins#1]
Repeatable error, timeline ends up right after an extrude

![image](https://github.com/user-attachments/assets/a24bf949-0fef-4f4c-bb88-561844b3e6a2)

```
Failed:
Traceback (most recent call last):
  File "C:/Users/apxrr/AppData/Roaming/Autodesk/Autodesk Fusion 360/MyScripts/Altered Design History Scripts/Design-History-Animation/Design-History-Animation.py", line 49, in notify
    timelapse.collectFrames()
  File "C:/Users/apxrr/AppData/Roaming/Autodesk/Autodesk Fusion 360/MyScripts/Altered Design History Scripts/Design-History-Animation/Design-History-Animation.py", line 311, in collectFrames
    if self.isNumericExtent(entity.extentOne):
                            ^^^^^^^^^^^^^^^^
  File "C:\Users/apxrr/AppData/Local/Autodesk/webdeploy/production/1a197c6e79bef01edef1dc4f317d9f597820e633/Api/Python/packages\adsk\fusion.py", line 70683, in _get_extentOne
    return _fusion.ExtrudeFeature__get_extentOne(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 2 : InternalValidationError : definition

```

**Comment by DoritoMojito** [comment]
Appears to be an issue caused by one side of the extrude having no target
